apply_sky:
  name: Apply Sky to Lights
  description: Apply the current sky color data (XY, RGB, or HSB) to selected lights.
  fields:
    target:
      name: Target
      description: Lights or areas to update.
      selector:
        target:
          entity:
            domain: light

    xy_color:
      name: XY Color
      description: CIE 1931 XY coordinates (list of two floats, e.g. [0.31, 0.33])
      example: [0.3029, 0.3397]
      selector:
        object: {}

    hs_color:
      name: HS Color
      description: Hue and Saturation in degrees and percent (e.g. [155, 10])
      example: [155, 10]
      selector:
        object: {}

    rgb_color:
      name: RGB Color
      description: Red, Green, Blue values (0–255)
      example: [146, 163, 156]
      selector:
        object: {}

    brightness:
      name: Brightness
      description: Brightness value (0–255)
      example: 163
      selector:
        number:
          min: 0
          max: 255
          step: 1

    brightness_pct:
      name: Brightness Percent
      description: Brightness as a percent (0–100)
      example: 64
      selector:
        number:
          min: 0
          max: 100
          step: 1

    source:
      name: Source
      description: Optional label or entity providing the color data (e.g. PiSky, MQTT)
      example: "pisky"
      selector:
        text: